zh_cn =
  signIn: "登录"
  signin: "登录"
  signOut: "退出"
  signUp: "注册"
  OR: "或者"
  forgotPassword: "忘记密码?"
  emailAddress: "Email地址"
  emailResetLink: "Email重置链接"
  dontHaveAnAccount: "还没有账号?"
  resetYourPassword: "重置密码"
  updateYourPassword: "更新密码"
  password: "密码"
  usernameOrEmail: "用户名或者邮箱"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "已经有账号"
  signUpWithYourEmailAddress: "使用你的Email注册"
  username: "用户名"
  optional: "可选"
  signupCode: "注册码"
  clickAgree: "点击注册的同时同意我们的"
  privacyPolicy: "隐私政策"
  terms: "使用条款"
  sign: "Sign"
  configure: "配置"
  with: "根据"
  createAccount: "注册"
  and: "和"
  "Match failed":  "匹配失败"
  "User not found":  "用户没有找到"
  "Email already exists." : "该Email已经被注册"
  "Internal server error" : "内部服务器错误"
  "Username already exists." : '该用户名已经被注册'
  "Incorrect password" : '密码不正确'

  error:
    minChar: "密码最少7个字符."
    pwOneLetter: "密码必须包含一个字母."
    pwOneDigit: "密码必须至少有一个数字."
    usernameRequired: "用户名是必须得."
    emailRequired: "Email是必须得."
    signupCodeRequired: "注册码为必填项."
    signupCodeIncorrect: "注册码不正确."
    signInRequired: "需要登录."
    usernameIsEmail: "用户名不能是Email地址."

T9n.map "zh-cn", zh_cn
